name: pr-spell-check
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Output File List
      run: |
        find . -type f -o -type d > file-list-output.txt
        cat file-list-output.txt
    - name: Check spelling
      uses: crate-ci/typos@master
      with: 
        config: .github/workflows/typos-config.toml